jobs:
  run-unit-test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout # Checkout your code from the repository
      - run:
          name: Set Node.js Version
          command: echo "export NODE_VERSION=$(jq -r '.engines.node' package.json)" >> $BASH_ENV
      - run:
          name: change Node.js Version
          command: sudo n $NODE_VERSION
      - run:
          name: Run Unit Tests
          command: npm test

workflows:
  version: 2
  test-workflow:
    jobs: 
      - run-unit-test