version: 2
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json"}}

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "package.json"}}
          paths:
            - node_modules

      - run:
          name: Run test
          command: npm test
          
workflows:
  version: 2
  test-workflow:
    jobs: 
      - build:
          filters:
            branches:
              only:
                - master
  