jobs:
  run-unit-test:
    steps:
      - checkout # Checkout your code from the repository
      - run:
          name: Set Node.js Version
          command: echo "export NODE_VERSION=$(jq -r '.engines.node' package.json)" >> $BASH_ENV
      - run:
          name: Run Unit Tests
          command: npm test
    docker:
      - image: circleci/node:$NODE_VERSION

workflows:
  version: 2
  test-workflow:
    jobs: 
      - run-unit-test: