jobs:
  run-unit-test:

    docker:
      - image: node:18.0.0 # Please update the node version if changed in package.json
    steps:
      - checkout # Checkout your code from the repository
      - run:
          name: Run Unit Tests
          command: npm test

workflows:
  version: 2
  test-workflow:
    jobs: 
      - run-unit-test