version: 2.1

workflows:
  test-deploy:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/node:14.13.0
    steps:
      - checkout  
      - run:
        name: create file
        command: node --help > ./test.file
      - run:
        name: runner
        command: node ./test.js
      